import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import java.awt.*;

public class WTMain
{
    private JPanel mainPanel;
    private JTree tree1;
    private JTable table1;

    public WTMain ()
    {
        tree1.addTreeSelectionListener(e ->
        {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode)
                    tree1.getLastSelectedPathComponent();
            DefaultTreeModel tm = (DefaultTreeModel) tree1.getModel();
            if (node == null)
            {
                return;
            }
            TreePath tp = e.getPath();

            String s = tp.toString()
                    .replace(", ", "")
                    .replace("[", "")
                    .replace("]", "");
            System.out.println(s);

            DirLister.updNode(tm, node, s);
            tree1.expandPath(tp);
        });
    }

    public static void main (String[] args)
    {
        JFrame frame = new JFrame("WTMain");
        DefaultTreeModel tm = DirLister.doIt("c:\\");
        WTMain wt = new WTMain();
        wt.tree1.setModel(tm);
        frame.setContentPane(wt.mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JSplitPane splitPane1 = new JSplitPane();
        mainPanel.add(splitPane1, BorderLayout.CENTER);
        table1 = new JTable();
        splitPane1.setRightComponent(table1);
        final JScrollPane scrollPane1 = new JScrollPane();
        splitPane1.setLeftComponent(scrollPane1);
        tree1 = new JTree();
        scrollPane1.setViewportView(tree1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return mainPanel;
    }
}

